service-name: mystorage
databases:
  - devstore
  - mystore

devstore:
  sync-interval: 10
  redis-addr: localhost
  redis-port: 6379
  db-storage: boltdb # boltdb|sniper
  db-name: devstore
  db-display-name: DevStore
  db-path: ../data/db/devstore/
  db-read-only: false
  container-name: devstorage
  bucket-list:
    - "urls"
    - "items"
  index-list:
    - "urls"
    - "items"

mystore:
  sync-interval: 10
  redis-addr: localhost
  redis-port: 6380
  db-storage: sniper # boltdb|sniper
  db-name: mystore
  db-display-name: MyStore
  db-path: ../data/db/mystore/
  db-read-only: false
  container-name: mystorage
  bucket-list:
    - "urls"
    - "items"
    - "options"
  index-list:
    - "urls"
    - "items"
