service-name: mystorage
databases:
  - devstore
  - mydbstore

devstore:
  sync-interval: 10
  redis-addr: localhost
  redis-port: 6379
  db-storage: boltdb # boltdb|sniper
  db-name: devstore
  db-display-name: DevStore
  db-path: ../data/db/devstore/
  db-read-only: false
  container-name: devstorage
  bucket-list:
    - "urls"
    - "items"
  index-list:
    - "urls"
    - "items"

mydbstore:
  sync-interval: 10
  redis-addr: localhost
  redis-port: 6380
  db-storage: sniper # boltdb|sniper
  db-name: mydbstore
  db-display-name: MyDbStore
  db-path: ../data/db/mydbstore/
  db-read-only: false
  container-name: mydbstorage
  bucket-list:
    - "urls"
    - "items"
    - "options"
  index-list:
    - "urls"
    - "items"
