version: '3.8'

services:
  mydbserver-builder:
    image: mydbserver-builder:latest
    build:
      context: ./
      args:
        SERVICE_COMMIT_ID: ${SERVICE_COMMIT_ID}
        SERVICE_BUILD: ${SERVICE_BUILD}
    container_name: mydbserver-builder